---
- hosts: all
  tasks:
   - name: "Cronjob Entry"
     cron:
       name: "#ibmssh_failed_log_reset 3 tetsing"
       user: root
       job: "/var/opt/ibmssh_failed_log_reset.sh Priya testing  >> /tmp/ibmssh_failed"
