---
- hosts: all
  tasks:
   - name: "Cronjob Entry"
     cron:
       name: "#ibmssh_failed_log_reset 4 tetsing"
       user: ec2-user
       job: "/var/opt/ibmssh_failed_log_reset.sh Priya testing  >> /tmp/ibmssh_failed"
